name: hifini@s0urcelab
on:
    workflow_dispatch:
    schedule:
      - cron: "0 2 * * *"
    watch:
      types: [started]
jobs:
  build:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BAIDU_COOKIE: ${{ secrets.HIFINI_COOKIE }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【音乐磁场签到】'
        if: env.HIFINI_COOKIE
        run: |
          node Task/hifini.js
        env:
          HIFINI_COOKIE: ${{ secrets.HIFINI_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}



