
name: mhdsp@feizao1
on:
    workflow_dispatch:
    schedule:
      - cron: "20 0,8 * * *"
    watch:
      types: [started]
jobs:
  build:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        MH_HD: ${{ secrets.MH_HD }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【陌嗨短视频】'
        if: env.MH_HD
        run: |
          node Task/mhdsp.js
        env:
          MH_HD: ${{ secrets.MH_HD }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
