name: ymz@cxk5
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0 16 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/chennfen/JavaScripts.git ~/JavaScripts
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/JavaScripts
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      
      - name: '【羊毛赚】'
        run: |
          cd ~/JavaScripts   
          node Task/ymz_node.js
 
