# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: yuedongzu@ziye3

on:
    workflow_dispatch:
    schedule:
      - cron: "0,30 * * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: yuedongzu

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        YDZ_yuedongzuTOKEN: ${{ secrets.YDZ_yuedongzuTOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【悦动族】'
        if: env.YDZ_yuedongzuTOKEN
        run: |
          node Task/yuedongzu.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}

