name: yuedongzu@ziye3
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0,30 0-14,22,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest   
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YDZ_CASH: ${{ secrets.YDZ_CASH }}
    steps:
      
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
      
      - name: '【悦动族】'
        run: |
          node Task/yuedongzu.js
          
          
        env:
           YDZ_CASH: ${{ secrets.YDZ_CASH }}
        
 
